"""Smart playlists and scrobble configs

Revision ID: 13e3131aa4a5
Revises: 7a3843ac28d7
Create Date: 2026-07-18 18:19:24.884560

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '13e3131aa4a5'
down_revision: str | None = '7a3843ac28d7'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('scrobble_configs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('listenbrainz_token', sa.String(length=100), nullable=True),
    sa.Column('lastfm_api_key', sa.String(length=64), nullable=True),
    sa.Column('lastfm_api_secret', sa.String(length=64), nullable=True),
    sa.Column('lastfm_session_key', sa.String(length=64), nullable=True),
    sa.Column('lastfm_username', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_scrobble_configs_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_scrobble_configs'))
    )
    op.create_table('smart_playlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('match', sa.String(length=3), nullable=False),
    sa.Column('rules', sa.Text(), nullable=False),
    sa.Column('sort', sa.String(length=20), nullable=False),
    sa.Column('max_tracks', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], name=op.f('fk_smart_playlists_owner_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_smart_playlists'))
    )
    with op.batch_alter_table('smart_playlists', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_smart_playlists_owner_id'), ['owner_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('smart_playlists', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_smart_playlists_owner_id'))

    op.drop_table('smart_playlists')
    op.drop_table('scrobble_configs')
    # ### end Alembic commands ###
