"""Artist info

Revision ID: 22c1644bbcf4
Revises: 87d8b3ef83aa
Create Date: 2026-07-18 14:19:52.998304

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '22c1644bbcf4'
down_revision: str | None = '87d8b3ef83aa'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('artist_info',
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.Column('bio', sa.Text(), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('source', sa.String(length=20), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_artist_info_artist_id_artists'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('artist_id', name=op.f('pk_artist_info'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('artist_info')
    # ### end Alembic commands ###
