"""Download fixes

Revision ID: 4bdc0376570e
Revises: dbfee3b7efb9
Create Date: 2026-07-18 09:32:13.606019

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = '4bdc0376570e'
down_revision: str | None = 'dbfee3b7efb9'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('download_fixes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('watch_id', sa.Integer(), nullable=False),
    sa.Column('song', sa.String(length=500), nullable=False),
    sa.Column('spotify_url', sa.String(length=500), nullable=True),
    sa.Column('youtube_url', sa.String(length=500), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['watch_id'], ['download_watches.id'], name=op.f('fk_download_fixes_watch_id_download_watches'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_download_fixes'))
    )
    with op.batch_alter_table('download_fixes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_download_fixes_watch_id'), ['watch_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('download_fixes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_download_fixes_watch_id'))

    op.drop_table('download_fixes')
    # ### end Alembic commands ###
