"""Saved queues

Revision ID: ef57d56cc4b6
Revises: 4bdc0376570e
Create Date: 2026-07-18 13:40:08.143627

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'ef57d56cc4b6'
down_revision: str | None = '4bdc0376570e'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('saved_queues',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('current_index', sa.Integer(), nullable=False),
    sa.Column('current_seconds', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_saved_queues_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_queues'))
    )
    with op.batch_alter_table('saved_queues', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_saved_queues_user_id'), ['user_id'], unique=False)

    op.create_table('saved_queue_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('queue_id', sa.Integer(), nullable=False),
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['queue_id'], ['saved_queues.id'], name=op.f('fk_saved_queue_items_queue_id_saved_queues'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_saved_queue_items_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_saved_queue_items'))
    )
    with op.batch_alter_table('saved_queue_items', schema=None) as batch_op:
        batch_op.create_index('ix_saved_queue_items_queue_position', ['queue_id', 'position'], unique=False)
        batch_op.create_index(batch_op.f('ix_saved_queue_items_track_id'), ['track_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('saved_queue_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_queue_items_track_id'))
        batch_op.drop_index('ix_saved_queue_items_queue_position')

    op.drop_table('saved_queue_items')
    with op.batch_alter_table('saved_queues', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_saved_queues_user_id'))

    op.drop_table('saved_queues')
    # ### end Alembic commands ###
