"""Track artists many-to-many and app settings

Revision ID: f284db053013
Revises: 7ed11bc44749
Create Date: 2026-07-17 23:56:20.945118

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f284db053013'
down_revision: str | None = '7ed11bc44749'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key', name=op.f('pk_app_settings'))
    )
    op.create_table('track_artists',
    sa.Column('track_id', sa.Integer(), nullable=False),
    sa.Column('artist_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['artist_id'], ['artists.id'], name=op.f('fk_track_artists_artist_id_artists'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['track_id'], ['tracks.id'], name=op.f('fk_track_artists_track_id_tracks'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('track_id', 'artist_id', name=op.f('pk_track_artists'))
    )
    # Preserve existing single-artist links before dropping the column
    op.execute(
        "INSERT INTO track_artists (track_id, artist_id) "
        "SELECT id, artist_id FROM tracks WHERE artist_id IS NOT NULL"
    )
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tracks_artist_id'))
        batch_op.drop_constraint(batch_op.f('fk_tracks_artist_id_artists'), type_='foreignkey')
        batch_op.drop_column('artist_id')

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('tracks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('artist_id', sa.INTEGER(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_tracks_artist_id_artists'), 'artists', ['artist_id'], ['id'], ondelete='SET NULL')
        batch_op.create_index(batch_op.f('ix_tracks_artist_id'), ['artist_id'], unique=False)

    # Best effort: keep one artist per track when collapsing back to a single column
    op.execute(
        "UPDATE tracks SET artist_id = ("
        "SELECT MIN(artist_id) FROM track_artists WHERE track_artists.track_id = tracks.id)"
    )
    op.drop_table('track_artists')
    op.drop_table('app_settings')
    # ### end Alembic commands ###
